winget install -e --id sharkdp.bat --source winget
winget install -e --id cURL.cURL --source winget
winget install -e --id eza-community.eza --source winget
winget install -e --id Fastfetch-cli.Fastfetch --source winget
winget install -e --id sharkdp.fd --source winget
winget install -e --id Git.Git --source winget
winget install -e --id jqlang.jq --source winget
winget install -e --id Neovim.Neovim --source winget
winget install -e --id OpenVPNTechnologies.OpenVPN --source winget
winget install -e --id BurntSushi.ripgrep.GNU --source winget
winget insatll -e --id GNU.Wget2 --source winget
