name: Continuous Integration

permissions:
  contents: read

on: pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # TODO: Pin action at full length commit SHA
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
